import { Platform, TextStyle } from "react-native";

export const theme = {
  colors: {
    background: "#f0fdf4",
    backgroundDeep: "#ecfccb",
    card: "#ffffff",
    cardElevated: "#fdfffd",
    ink: "#064e3b",
    inkSoft: "#065f46",
    muted: "#475569",
    mutedSoft: "#64748b",
    inkOnDark: "#ffffff",
    inkOnDarkSoft: "#d1fae5",
    inkOnDarkMuted: "#a7f3d0",
    bgEmerald: "#064e3b",
    bgEmeraldMid: "#14532d",
    bgEmeraldDeep: "#166534",
    brand: "#10b981",
    brandDark: "#059669",
    brandDeep: "#047857",
    brandSoft: "#d1fae5",
    brandTint: "#a7f3d0",
    accent: "#10b981",
    accentSoft: "#d1fae5",
    aura: "#fde047",
    auraDeep: "#facc15",
    auraSoft: "#fef9c3",
    fire: "#ff6b35",
    fireDeep: "#f59e0b",
    fireSoft: "#ffedd5",
    heart: "#ef4444",
    heartSoft: "#fee2e2",
    danger: "#ef4444",
    dangerSoft: "#fee2e2",
    success: "#10b981",
    successSoft: "#d1fae5",
    warning: "#f59e0b",
    border: "#d1fae5",
    borderStrong: "#a7f3d0",
    borderDark: "rgba(255, 255, 255, 0.18)",
    surface: "#dcfce7",
    surfaceMuted: "#f5fbf7",
    surfaceAlt: "#edf8f2",
    surfaceSubtle: "#f7fbf9",
    surfaceQuiet: "#f1f5f2",
    surfaceDark: "rgba(255, 255, 255, 0.08)",
    surfaceDarkElevated: "rgba(255, 255, 255, 0.14)",
    locked: "#94a3b8",
    lockedSurface: "#f1f5f9",
    gold: "#fde047",
    goldSoft: "#fef9c3",
    silver: "#cbd5e1",
    silverSoft: "#e2e8f0",
    bronze: "#f59e0b",
    bronzeSoft: "#fef3c7",
    overlay: "rgba(6, 78, 59, 0.55)",
    starGlow: "rgba(253, 224, 71, 0.9)",
    starSoft: "rgba(255, 255, 255, 0.7)",
  },
  radius: {
    full: 999,
    lg: 24,
    md: 18,
    sm: 12,
    xs: 8,
  },
  fonts: {
    urdu: "NotoNastaliqUrdu_400Regular",
    urduBold: "NotoNastaliqUrdu_700Bold",
    serif: Platform.select({ ios: "Georgia", android: "serif", default: "Georgia" }) as string,
  },
  weights: {
    regular: "400" as TextStyle["fontWeight"],
    medium: "500" as TextStyle["fontWeight"],
    semibold: "600" as TextStyle["fontWeight"],
    bold: "700" as TextStyle["fontWeight"],
    extrabold: "800" as TextStyle["fontWeight"],
    display: "900" as TextStyle["fontWeight"],
  },
  shadows: {
    soft: Platform.select({
      ios: {
        shadowColor: "#064e3b",
        shadowOpacity: 0.1,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 8 },
      },
      android: { elevation: 3 },
      default: {},
    }) as object,
    lift: Platform.select({
      ios: {
        shadowColor: "#064e3b",
        shadowOpacity: 0.18,
        shadowRadius: 22,
        shadowOffset: { width: 0, height: 12 },
      },
      android: { elevation: 8 },
      default: {},
    }) as object,
    glow: Platform.select({
      ios: {
        shadowColor: "#fde047",
        shadowOpacity: 0.45,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 0 },
      },
      android: { elevation: 6 },
      default: {},
    }) as object,
  },
  gradients: {
    background: ["#f0fdf4", "#ecfccb", "#fef9c3"] as const,
    hero: ["#064e3b", "#14532d", "#166534"] as const,
    heroDeep: ["#022c22", "#064e3b", "#065f46"] as const,
    aura: ["#fde047", "#facc15"] as const,
    fire: ["#ff6b35", "#f59e0b"] as const,
    surface: ["#ffffff", "#d1fae5"] as const,
    sunrise: ["#fff6df", "#ffd9a8"] as const,
  },
};

export type Theme = typeof theme;
