import { Platform, TextStyle } from "react-native";

export const theme = {
  colors: {
    background: "#eef8f2",
    backgroundDeep: "#dff0e6",
    card: "#ffffff",
    cardElevated: "#fdfffd",
    ink: "#143b2f",
    inkSoft: "#274d40",
    muted: "#5d7e71",
    mutedSoft: "#7d9c90",
    brand: "#1f8f67",
    brandDark: "#15684b",
    brandSoft: "#eaf8ef",
    brandTint: "#d3edde",
    accent: "#8fd16f",
    accentSoft: "#dff2cf",
    danger: "#b85c4a",
    dangerSoft: "#f8ece7",
    success: "#258a63",
    successSoft: "#e7f7ee",
    warning: "#d6a23a",
    border: "#d6eadf",
    borderStrong: "#beddca",
    surface: "#e4f4eb",
    surfaceMuted: "#f5fbf7",
    surfaceAlt: "#edf8f2",
    surfaceSubtle: "#f7fbf9",
    surfaceQuiet: "#f1f5f2",
    locked: "#c7d6ce",
    lockedSurface: "#edf2ef",
    gold: "#e4b94a",
    goldSoft: "#fbe7a3",
    silver: "#a8b6c0",
    silverSoft: "#dde4e9",
    bronze: "#b87547",
    bronzeSoft: "#e9c5a8",
    overlay: "rgba(20, 59, 47, 0.45)",
  },
  radius: {
    full: 999,
    lg: 24,
    md: 18,
    sm: 12,
    xs: 8,
  },
  fonts: {
    urdu: "NotoNastaliqUrdu_400Regular",
    urduBold: "NotoNastaliqUrdu_700Bold",
  },
  weights: {
    regular: "400" as TextStyle["fontWeight"],
    medium: "500" as TextStyle["fontWeight"],
    semibold: "600" as TextStyle["fontWeight"],
    bold: "700" as TextStyle["fontWeight"],
    extrabold: "800" as TextStyle["fontWeight"],
    display: "900" as TextStyle["fontWeight"],
  },
  shadows: {
    soft: Platform.select({
      ios: {
        shadowColor: "#0e3a2c",
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
      },
      android: { elevation: 2 },
      default: {},
    }) as object,
    lift: Platform.select({
      ios: {
        shadowColor: "#0e3a2c",
        shadowOpacity: 0.14,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
      },
      android: { elevation: 6 },
      default: {},
    }) as object,
  },
  gradients: {
    background: ["#f4fbf6", "#dff0e6", "#cfe6d8"] as const,
    hero: ["#1f8f67", "#15684b"] as const,
    surface: ["#ffffff", "#eaf8ef"] as const,
    sunrise: ["#fff6df", "#ffd9a8"] as const,
  },
};

export type Theme = typeof theme;
